In [1]:
import numpy as np

# 1. Какое свойство содержит количество элементов массива по измерениям?

shape

# 2. Напишите функцию, создающую ndarray из массива [0, 1, 2, 3, 4]

In [4]:
x = np.array([0,1,2,3,4])
print(type(x), x)

<class 'numpy.ndarray'> [0 1 2 3 4]


# 3. Как создать нулевой 4-мерный вектор?

In [5]:
x = np.zeros(4)
x

array([0., 0., 0., 0.])

# 4. Как создать единичную диагональную матрицу 3х4?

In [30]:
x = np.zeros(shape=(3,4))
for i in range(min(x.shape)):
    x[i][i] = 1
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# 5. Сколько операций умножения матриц существует в numpy?

In [31]:
y = np.ones(shape=(4,3))
x@y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
x.dot(y)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.dot(x,y)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Получается, 3

# 6. Напишите инструкцию, выбирающую каждый третий элемент массива А начиная с 10-го и заканчивая 45-м

In [42]:
A = np.random.uniform(size=50)
A

array([0.51348315, 0.98483545, 0.70794221, 0.53105975, 0.42463672,
       0.39108564, 0.66407129, 0.99216686, 0.35639378, 0.5235956 ,
       0.56978172, 0.91117246, 0.44229257, 0.20005073, 0.03725484,
       0.50031737, 0.32828802, 0.35460254, 0.46370162, 0.37007034,
       0.8384894 , 0.97608485, 0.35723615, 0.24367145, 0.64624485,
       0.60406327, 0.36079841, 0.9314382 , 0.63807381, 0.03357142,
       0.3615357 , 0.53986255, 0.73287851, 0.33225028, 0.15623805,
       0.32594519, 0.79075828, 0.59698473, 0.47315439, 0.50379149,
       0.75598208, 0.37221555, 0.86412824, 0.90899664, 0.49349248,
       0.34963968, 0.37179135, 0.61756198, 0.68811937, 0.36947498])

In [44]:
A[10:46:3]

array([0.56978172, 0.20005073, 0.32828802, 0.37007034, 0.35723615,
       0.60406327, 0.63807381, 0.53986255, 0.15623805, 0.59698473,
       0.75598208, 0.90899664])

# 7. Напишите инструкцию создания матрицы 4х3 из плоского массива из 12 элементов

In [45]:
A = np.ones(12)
A

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
A = A.reshape(4,3)
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])